### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ghost** [iqaan/epilepsy-cnn#1]
Hi, is there an alternative link for the dataset you usedin your exaample? Bonn hosts no more those datasets and the eu centralised database charges a wabbling 3K euro for access. many thanks!''richardson

**Comment by iqaan** [comment]
> Hi, is there an alternative link for the dataset you usedin your exaample? Bonn hosts no more those datasets and the eu centralised database charges a wabbling 3K euro for access. many thanks!''richardson

Let me know how I can share it with you.
